apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-authors
  labels:
    app: app-authors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-authors
  template:
    metadata:
      labels:
        app: app-authors
    spec:
      containers:
        - name: app-authors
          image: docker.io/reymon4/app_authors_examen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCE_SERVERNAME
              value: 192.168.1.55
            - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCE_PORTNUMBER
              value: "5432"
            - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCE_DATABASENAME
              value: distribuida
            - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCE_USER
              value: postgres
            - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCE_PASSWORD
              value: root
            - name: JAVAX_SQL_DATASOURCE_DS1_DATASOURCECLASSNAME
              value: org.postgresql.ds.PGSimpleDataSource
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-books
  labels:
    app: app-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-books
  template:
    metadata:
      labels:
        app: app-books
    spec:
      containers:
        - name: app-books
          image: docker.io/reymon4/app_books:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://192.168.1.55:5432/distribuida
            - name: QUARKUS_DATASOURCE_USERNAME
              value: postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: root
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: QUARKUS_HTTP_CORS
              value: "true"
            - name: QUARKUS_HTTP_CORS_ORIGIN
              value: "*"
            - name: QUARKUS_HTTP_CORS_METHODS
              value: "GET,POST,PUT,DELETE"
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/reymon4/frontend_examen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: VUE_APP_API_BOOKS_SERVER
              value: http://app-books
            - name: VUE_APP_API_BOOKS_PORT
              value: "8080"
            - name: VUE_APP_API_BOOKS_PATH
              value: /books
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080